### ISSUE TITLE
Create a 'fake server user' generator

### ISSUE THREAD

**Issue by 1ForeverHD** [nanoblox/core#100]
To do:
- [x] create a method which mimics a caller user to allow for third-party executions (such as from discord)
- [x] convert all SettingService ``optionalPlayer`` parameters to ``optionalUser``

User properties to mimic:
- ``userId``
- ``name``
- ``displayName`` --!!! add to user
- ``temp.parsePatterns`` (see CommandService for details)
- ``roles = {}`` - by default, give creator role

plus a lot more I imagine

**Comment by Hasnain123Raza** [comment]
Please also mimic **playerIdentifier**, **playerDefinedSearch**, and **playerUndefinedSearch**.

**Comment by 1ForeverHD** [comment]
Plus convert the following to ``optionalUser`` (instead of ``optionalPlayer``)
- [ ] All of the SettingService methods with the 'optionalPlayer' parameter
- [ ] ``function Parser.getPlayersFromString(playerString, optionalPlayer)``
- [ ] ``function Parser.parseMessage(message, optionalPlayer)``
- [ ] ``function ParsedData.parsedDataSetRequiresQualifierFlag(parsedData, optionalPlayer)``
