### ISSUE TITLE
Question (How to add???)

### ISSUE THREAD

**Issue by Vadym-beep** [nanoblox/core#113]
Please tell me, how to add nanoblox to my Roblox game???
May be I need to load core/remodel/development.rblx to roblox???
Idk how to do it!

**Comment by optimisticside** [comment]
Nanoblox is currently in development. It is not yet complete. If you want an admin system for your game, It's recommended you use [HD Admin](https://www.roblox.com/library/857927023/HD-Admin) for now.

**Comment by Vadym-beep** [comment]
@optimisticside Ok
