### ISSUE TITLE
Easy way to share modules and add-ons

### ISSUE THREAD

**Issue by Lucke0051** [nanoblox/core#18]
I have sometimes made modules that I feel like for someone who doesn't know how to program it is maybe a little hard to insert it if you have to like insert the main module, edit the parser and then add the module under it. A way to just add it in a folder without having to insert the main module would be nice. For example just add a folder under custom features.

Then to add a module simply put it in there and the main module will require it.
Also if you need to change like some core parts of the system, allowing the user to override some modules like the parser would be awesome.
You could for example just add a string value or something in that custom module named like "Override" and then the value could be "Parser" the main module would then look in the custom modules folder before requireing the core parser.

This would make it really easy for users in all ages and skill levels to add some custom functionaliy.
![addons](https://user-images.githubusercontent.com/30857678/85952331-cb7e2280-b968-11ea-8378-82ef281c4e94.png)

Thanks, Lucke.

**Comment by Exo-Byte** [comment]
I think that this is a good idea, and may be useful in more in-depth customization of HD Admin.

**Comment by 1ForeverHD** [comment]
Nice idea! I'll explore the specifics behind this further down the road.
