### ISSUE TITLE
Merge Loader Extensions into Core

### ISSUE THREAD

**Issue by 1ForeverHD** [nanoblox/core#70]
- [x] have extensions.commands  ``Directory.move`` to realcore.server.commands
- [x] then have all of extensions.core merge into the corresponding areas
- [x] ensure command descendants also merge correctly, such as the 'Client' module, it's assets, the commands assets, etc
- [x] when merging modules, consider converting the original into 'NanobloxToConvert' then putting the new one into the original spot - if doing this, methods from the original should only be merged if corresponding == nil)
- [x] full test merging (core, commands, assets, folders, etc)
- [x] setup the command core module initialiser
  - [x] have any 'Client' modules renamed to their parents name and moved under 'ClientCommands' under shared
  - [x] within the Command module on init, register all commands and tags
- [x] setup client commands basic
- [x] respond to #18 and mark as closed

**Comment by supeman334** [comment]
> * [x]  have extensions.commands  `Directory.move` to realcore.server.commands
> * [x]  then have all of extensions.core merge into the corresponding areas
> * [x]  ensure command descendants also merge correctly, such as the 'Client' module, it's assets, the commands assets, etc
> * [x]  when merging modules, consider converting the original into 'NanobloxToConvert' then putting the new one into the original spot - if doing this, methods from the original should only be merged if corresponding == nil)
> * [x]  full test merging (core, commands, assets, folders, etc)
> * [x]  setup the command core module initialiser
>   
>   * [x]  have any 'Client' modules renamed to their parents name and moved under 'ClientCommands' under shared
>   * [x]  within the Command module on init, register all commands and tags
> * [x]  setup client commands basic
> * [x]  respond to #18 and mark as closed

This to mine roblox supeman334 account
