### ISSUE TITLE
Consider and provide support for 'Client Settings'

### ISSUE THREAD

**Issue by 1ForeverHD** [nanoblox/core#81]
- [x] setup new PlayerSearch enum and push up the new system and user/client identifier/name settings
- [x] Consider changing the name to 'local' instead of client (maybe not)
- [x] Determine how client settings will be checked for and retrieved (maybe a method getClientSetting)
- [x] Determine how this will be integrated into the parser (e.g. prefixes, which can be customised by the client)

**Comment by Alidonis** [comment]
Heya, heres a few of my opinions :
1st : do NOT rename client. it's  better to understand as client than local.
2nd : _ModuleScript's_ your friend.
3rd : datastores? yeah no for this one don't hope alot for me to help
