### ISSUE TITLE
is that even a loader?

### ISSUE THREAD

**Issue by Alidonis** [nanoblox/core#83]
![Script - Roblox Studio 08-03-21 17_02_03](https://user-images.githubusercontent.com/64419217/110346660-0d02b980-8030-11eb-8d79-51673ae3ab32.png)

**Comment by optimisticside** [comment]
No, it's not a loader. It's just a placeholder. Nanoblox is still currently under development and the loader is at a low priority.

**Comment by Alidonis** [comment]
> No, it's not a loader. It's just a placeholder. Nanoblox is still currently under development and the loader is at a low priority.

Oh
But i need to get it working for testing it, how will i script a loader myself?

**Comment by 1ForeverHD** [comment]
In answer to your question, no, that was a test repo. The actual loader is integrated into nanoblox/plugin.

You won't be able to test anything yet, and I'd recommend waiting for the documentation which helps explain all the components, internal frameworks, practises, etc
