### ISSUE TITLE
Favicon becomes invisible on Chrome light mode

### ISSUE THREAD

**Issue by sleepiie** [nanoblox/core#85]
<img width="371" alt="Screen Shot 2021-04-02 at 10 40 43 PM" src="https://user-images.githubusercontent.com/74518502/113465754-9e353800-9404-11eb-804e-0d98479b70f2.png">
<img width="371" alt="Screen Shot 2021-04-02 at 10 40 36 PM" src="https://user-images.githubusercontent.com/74518502/113465764-ab522700-9404-11eb-8dc6-46bbd262381e.png">

**Comment by 1ForeverHD** [comment]
Good spot, resolved.
